# Generated by Django 3.2.15 on 2022-12-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=30)),
                ('Text_area', models.TextField(max_length=1500)),
            ],
        ),
    ]
